[package]
name = "ayx-rs"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
clap.workspace = true
clap_complete = "4"
reqwest.workspace = true
roxmltree.workspace = true
serde.workspace = true
serde_yaml.workspace = true
serde_json.workspace = true
ratatui = "0.30"
crossterm = "0.29"
ayx_server_api = { package = "ayx-server-api", path = "../ayx-server-api" }
ayx-core = { path = "../ayx-core" }
ayx-workflow = { path = "../ayx-workflow" }
ayx-one = { path = "../ayx-one" }
ayx_one_api = { package = "ayx-one-api", path = "../ayx-one-api" }
ayx-server = { path = "../ayx-server" }
ayx-registry = { path = "../ayx-registry" }
self_update = "0.44.0"

[dev-dependencies]
tempfile.workspace = true
regex = "1"

[[bin]]
name = "ayx"
path = "src/main.rs"
