[package]
name = "ayx-rs"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
clap.workspace = true
clap_complete.workspace = true
reqwest.workspace = true
roxmltree.workspace = true
serde.workspace = true
serde_yaml.workspace = true
serde_json.workspace = true
crossterm.workspace = true
ratatui.workspace = true
url.workspace = true
ayx_server_api = { package = "ayx-server-api", path = "../ayx-server-api" }
ayx-core = { path = "../ayx-core" }
ayx-workflow = { path = "../ayx-workflow" }
ayx-one = { path = "../ayx-one" }
ayx_one_api = { package = "ayx-one-api", path = "../ayx-one-api" }
ayx-server = { path = "../ayx-server" }
ayx-registry = { path = "../ayx-registry" }
self_update.workspace = true
tokio.workspace = true
base64.workspace = true

[dev-dependencies]
tempfile.workspace = true
regex.workspace = true
reqwest = { workspace = true }

[[bin]]
name = "ayx"
path = "src/main.rs"
