[package]
name = "ayx-one"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
anyhow.workspace = true
ayx-core = { path = "../ayx-core" }
serde_json.workspace = true
ayx_one_api = { package = "ayx-one-api", path = "../ayx-one-api" }
