[package]
name = "ayx-workflow"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
roxmltree.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
walkdir.workspace = true
zip = { workspace = true }
lzf = "1"
snap = "1"
tempfile = "3"
sha2.workspace = true
