[package]
name = "ayx-workflow"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
anyhow.workspace = true
roxmltree.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
walkdir.workspace = true
zip = { workspace = true }
lzf.workspace = true
snap.workspace = true
tempfile.workspace = true
sha2.workspace = true
